# Generated by Django 4.1.7 on 2023-03-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_resumeportfolio_project_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeportfolio',
            name='project_link',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
