# Generated by Django 4.1.7 on 2023-03-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_resumeportfolio_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumetitle',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', upload_to='thumbnail_profile'),
        ),
    ]
